AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple serverless application

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs18.x
      CodeUri: ../dist/
      MemorySize: 128
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole
