name: C++ CI Workflow

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      deployment_method:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.21.2'

      - name: Install Dependencies
        run: |
          sudo apt-get install -y build-essential

      - name: Build C++ Project
        run: cmake . && make

      - name: Run Tests
        if: inputs.build_type == 'ci'
        run: echo "No tests defined for C++ app"

      - name: Package Artifact
        run: |
          mkdir -p dist
          tar -czvf dist/cpp-app.tar.gz ./cpp-app
        if: inputs.build_type == 'ci'

      - name: Deploy
        run: echo "Deploying using ${{ inputs.deployment_method }}"