name: C++ CI Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build C++ app
        run: |
          cd apps/cpp-app
          make