name: Bootstrap Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      technology: ${{ steps.parse.outputs.technology }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yq

      - name: Parse Blueprint
        id: parse
        run: |
          bash utils/parse-blueprint.sh

  validate_branch:
    needs: bootstrap
    uses: ./.github/workflows/validate-branch.yml
    secrets: inherit

  ci_pipeline:
    needs: bootstrap
    uses: ./.github/workflows/${{ needs.bootstrap.outputs.technology }}-ci.yml
    secrets: inherit
