name: Python CI Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r apps/python-app/requirements.txt

      - name: Run Tests
        run: pytest apps/python-app/

      - name: Load Stages (optional)
        run: |
          if [ -f output_stages.json ]; then
            cat output_stages.json
          else
            echo "Warning: output_stages.json not found. Skipping..."
          fi
