name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r python-app/requirements.txt

      - name: Parse Blueprint
        run: |
          echo "Running Blueprint Parser..."
          if python3 scripts/parse_blueprint.py; then
            echo "Blueprint parsed successfully!"
          else
            echo "parse_blueprint.py failed. Creating empty output_stages.json"
            echo '{}' > output_stages.json
          fi

      - name: Load Stages
        run: |
          if [ ! -f output_stages.json ]; then
            echo "output_stages.json still missing! Creating empty file."
            echo '{}' > output_stages.json
          fi
          echo "output_stages.json content:"
          cat output_stages.json

      - name: Run Tests
        run: |
          echo "Running Python tests..."
          python3 -m unittest discover python-app/
          echo "Tests completed."

      - name: Upload output_stages.json
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: output_stages
          path: output_stages.json
